goserviceapp/src/main/java/com/soulcode/goserviceapp/controller/AuthController.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Cliente.java
goserviceapp/src/main/resources/templates/cadastroCliente.html
goserviceapp/src/main/resources/templates/fragments/layout.html
goserviceapp/src/main/resources/templates/login.html

Construção e mapeamento da página Cadastro e Login.

---

goserviceapp/src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
goserviceapp/src/main/resources/templates/servicosAdmin.html

construção e mapeamento da página de serviços.

---

src/main/resources/application.properties

Atualização da conexão do banco de dados.

---

src/main/resources/application.properties

conexão com o mongoDB

---

src/main/resources/application.properties

fix: conexão com o mongodb

---

src/main/resources/static/css/main.css
src/main/resources/templates/cadastroCliente.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/login.html

Imagens do cliente aplicada como logo na página

logo aplicada na pagina

---

src/main/java/com/soulcode/goserviceapp/config/SecurityConfig.java
src/main/java/com/soulcode/goserviceapp/controller/DuvidasController.java
src/main/resources/application.properties
src/main/resources/static/css/main.css
src/main/resources/templates/duvidasFrequentes.html

Perguntas frequentes

---

src/main/resources/templates/agendaPrestador.html
src/main/resources/templates/historicoCliente.html

Inclusão do modal na agenda do prestador para exibir detalhes do cliente

---

src/main/resources/static/css/main.css
src/main/resources/templates/home.html

Implementação de cards na página inicial

Criação dos cards na página principal

---

src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java

Criado a query para consultar o numero de agendamentos por status.

Consulta status de agendamentos

---

src/main/java/com/soulcode/goserviceapp/domain/AgendamentoLog.java
src/main/java/com/soulcode/goserviceapp/repository/AgendamentoLogRepository.java
src/main/java/com/soulcode/goserviceapp/service/AgendamentoLogService.java

criação do sistema de logs para os agendamentos

---

src/main/java/com/soulcode/goserviceapp/domain/Endereco.java
src/main/java/com/soulcode/goserviceapp/domain/Usuario.java
src/main/java/com/soulcode/goserviceapp/repository/EnderecoRepository.java
src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
src/main/java/com/soulcode/goserviceapp/service/EnderecoService.java
src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
src/main/java/com/soulcode/goserviceapp/service/exceptions/EnderecoNaoEncontradoException.java

Feita a tabela endereço para clientes e prestadores

criação da tabela endereço

---

src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
src/main/resources/templates/servicosAdmin.html

Feita a tabela com o percentual em gráfico de status de agendamentos

---

src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java

Feito a consulta para limitar até 10 usuarios por página

---

src/main/java/com/soulcode/goserviceapp/controller/ClienteController.java
src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java
src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
src/main/java/com/soulcode/goserviceapp/service/exceptions/HorarioAgendamentoNaoDisponivelException.java

Feita verificação de disponibilidade de horário por prestador e lançamento de erro

---

src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
src/main/java/com/soulcode/goserviceapp/repository/AdministradorRepository.java
src/main/java/com/soulcode/goserviceapp/service/AdministradorService.java
src/main/resources/templates/dadosAdmin.html
src/main/resources/templates/duvidasFrequentes.html
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/header.html

Criação e mapeamento da pagina dados admin

---

pom.xml
src/main/java/com/soulcode/goserviceapp/controller/ClienteController.java
src/main/java/com/soulcode/goserviceapp/controller/PrestadorController.java
src/main/java/com/soulcode/goserviceapp/domain/Mensagem.java
src/main/java/com/soulcode/goserviceapp/repository/MensagemRepository.java
src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
src/main/java/com/soulcode/goserviceapp/service/ClienteService.java
src/main/java/com/soulcode/goserviceapp/service/MensagemService.java
src/main/java/com/soulcode/goserviceapp/service/exceptions/MensagemNaoEncontradaException.java
src/main/resources/static/css/main.css
src/main/resources/templates/agendaPrestador.html
src/main/resources/templates/chatCliente.html
src/main/resources/templates/chatPrestador.html
src/main/resources/templates/historicoCliente.html

criação do chat entre prestador em cliente.

---

src/main/java/com/soulcode/goserviceapp/domain/Mensagem.java

Add os Metodos Gettrer e Setter no domain Mensagem.

---

src/main/java/com/soulcode/goserviceapp/repository/ServicoRepository.java

Criação da consulta de forma paginada para os serviços.

---

src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java

Criação de query para retornar os agendamento de forma paginada.

---

src/main/java/com/soulcode/goserviceapp/controller/ClienteController.java
src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java
src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
src/main/resources/templates/historicoCliente.html

Implementação do filtro de busca do cliente

---

src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
src/main/resources/templates/usuariosAdmin.html

Filtragem e consulta de todos usuarios pelo nome na página de administrador

---

src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java

Cacheamento com Redis

---

src/main/java/com/soulcode/goserviceapp/domain/Usuario.java
src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
src/main/resources/application.properties

Adição do rediscache2
@Cacheable comentado com orientações do professor

Correção da configuração do redis

---

src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
src/main/resources/templates/usuariosAdmin.html

- Criação dos métodos em AdministradorController:
- Inclusão das páginas no rodapé da tabela de usuários:

Inclusão da páginação de usuários na área do administrador.

---

src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
src/main/java/com/soulcode/goserviceapp/repository/ServicoRepository.java
src/main/java/com/soulcode/goserviceapp/service/ServicoService.java
src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
src/main/resources/templates/servicosAdmin.html

- Correção da query para retorno da consulta em páginas:
- Inclusão do método para busca por paginas:
- Inclusão da busca total de página por quantidade de registros na tabela serviços: 
- Mapeamento das rotas no AdministradorController:
- Inclusão das páginas no rodapé do tabela de serviços na área do administrador:

Inclusão de paginação de serviços na área do administrado
